## Solar Thermal CalculationThe model uses a single temperature to characterize the solar field and relies on the EN12975 standard to characterize the solar thermal collector performance. The approach is based on Chapter 6 and Chapter 10 of “Solar Engineering of Thermal Processes”, by J.A Duffie and W.A. Beckman.  
The model can simulate the performance of the solar field collector, and then connect it to a thermal storage component or heat exchanger model to incorporate it in a model or a functional system.


First, some imports:

In [2]:
import pandas as pd

from pandapower.timeseries.data_sources.frame_data import DFData
from pandaprosumer.create import create_empty_prosumer_container, create_period
from pandaprosumer.create_controlled import (create_controlled_const_profile, create_controlled_solar_thermal)
from pandaprosumer.mapping import GenericMapping
from pandaprosumer.run_time_series import run_timeseries

In [3]:
data = pd.read_excel('data/senergy_nets_example_solar_thermal.xlsx')
data = data.iloc[0:96].copy()
data["time"] = pd.to_datetime(data["time"], format="%Y%m%d:%H%M")
data.set_index("time", inplace=True)
start = '2005-01-01 00:30:00'
end = '2005-01-05 00:29:59'
time_resolution_s = 3600        # 15 min
frequency = '60min'

Similarly to pandapower and pandapipes, the input for a time-series calculation has to be converted to the DFData format, which we imported before.

In [4]:
dur = pd.date_range(start=start, end=end, freq=frequency, tz='utc')
data.index = dur
data_input = DFData(data)
data.head()

,Beam Solar Radiation [W/m2],Diffuse Solar Radiation [W/m2],Ground Solar Radiation [W/m2],Radiation incidence angle [deg],Ambient temperature [C],Inlet temperature [C],Inlet mass flow rate [kg/h]
2005-01-01 00:30:00+00:00,0.0,0.0,0.0,0.0,-2.44,20.00,0
2005-01-01 01:30:00+00:00,0.0,0.0,0.0,0.0,-2.39,18.25,0
2005-01-01 02:30:00+00:00,0.0,0.0,0.0,0.0,-2.44,16.50,0
2005-01-01 03:30:00+00:00,0.0,0.0,0.0,0.0,-2.37,14.75,0
2005-01-01 04:30:00+00:00,0.0,0.0,0.0,0.0,-2.42,13.00,0

In [5]:
input_params = ['Beam Solar Radiation [W/m2]',
                 'Diffuse Solar Radiation [W/m2]',
                 'Ground Solar Radiation [W/m2]',
                 'Radiation incidence angle [deg]',
                 'Ambient temperature [C]',
                 'Inlet temperature [C]',
                 'Inlet mass flow rate [kg/h]']
result_params = [
                    "beam_solar_radiation_cp",
                    "diffuse_solar_radiation_cp",
                    "ground_solar_radiation_cp",
                    "radiation_incidence_angle_cp",
                    "ambient_temperature_cp",
                    "inlet_temperature_cp",
                    "inlet_mass_flow_rate_cp"
                ]

st_params = {}

prosumer = create_empty_prosumer_container()

period = create_period(prosumer, time_resolution_s, start, end, 'utc', 'default')

cp_index = create_controlled_const_profile(
    prosumer, input_params, result_params, data_input, period)

st_index = create_controlled_solar_thermal(prosumer, name="solar_thermal_plant", level=1, order=0, **st_params)

In [6]:
GenericMapping(
    prosumer,
    initiator_id=cp_index,
    initiator_column=["beam_solar_radiation_cp",
                    "diffuse_solar_radiation_cp",
                    "ground_solar_radiation_cp",
                    "radiation_incidence_angle_cp",
                    "ambient_temperature_cp",
                    "inlet_temperature_cp",
                    "inlet_mass_flow_rate_cp"],
    responder_id=st_index,
    responder_column=['beam_solar_radiation_w_m2',
                      'diffuse_solar_radiation_w_m2',
                      'ground_solar_radiation_w_m2',
                      'radiation_incidence_angle_deg',
                      'ambient_temperature_C',
                      'inlet_temperature_C',
                      'inlet_mass_flow_rate_kg_h',
                      ]
)

In [7]:
run_timeseries(prosumer)

100%|██████████| 96/96 [00:00<00:00, 411.57it/s]

1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.430007050528786
73.07948521739131
-2.4399999999999964
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.410359576968272
71.55847605170388
-2.3900000000000032
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.430007050528786
73.07948521739131
-2.4399999999999964
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.402500587544065
70.95034745005876
-2.3700000000000023
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.422148061104583
72.47096366627495
-2.4200000000000044
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.319981198589893
64.57448686251469
-2.1600000000000024
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.4457250293772
74.29699985898941
-2.480000000000007
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 303.6453352291993
0.19647473560517037
30.103858989424204
-2248.8995920298494
54.97778593138565
0.019647473560517038
2.9471210340775555
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 573.354063234683
0.19325183302494442
1366.3867930473957
-23466.352069837787
17.132504782143393
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 753.8258369177131
0.19325183302494442
1365.0533553995235
-30381.175937238793
22.186713474163536
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 832.0423383523348
0.19325183302494442
1364.0407157944728
-37534.191718091926
27.410468510356782
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 852.115351730353
0.19325183302494442
1363.6271568717993
-44371.92085520938
32.39094060337832
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 711.1121198087012
0.19325183302494442
1363.3952546721696
-48096.7541969675
35.10253642955261
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 526.25197873389
0.19325183302494442
1363.306358828978
-49350.71615955578
36.015417153840225
0.019325183302494442
2.898777495374166
1
1
[1, 1, 1]
gt: 274.79129126111974
0.19647473560517037
29.14113278495887
-2103.214716552385
53.136758456580935
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 13.575241799553899
0.19647473560517037
26.57124324324324
-309.48354739375833
10.786930875292043
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
26.634115158636895
-202.54022505287895
7.220000000000002
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
26.968122209165685
-179.75927417156285
6.369999999999993
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.290340775558164
-157.51330434782608
5.5499999999999945
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.832611045828436
-119.47846759106932
4.169999999999998
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
28.39059929494712
-79.55998824911869
2.7500000000000004
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
28.925010575793184
-40.58537353701527
1.3899999999999963
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.32581903642773
-10.877450434782608
0.36999999999999783
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.490857814336074
1.474051703877791
-0.05000000000000215
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.06456404230317
44.94950965922444
-1.5100000000000016
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.253179788484136
59.425768178613396
-1.990000000000004
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.288545240893065
62.15014580493537
-2.0799999999999987
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.355346650998822
67.30487661574617
-2.2499999999999973
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.382853113983547
69.43071360752056
-2.3200000000000003
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.367135135135133
68.21571384253818
-2.2799999999999985
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.561588719153935
6.788771891891892
-0.23000000000000084
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 315.0951975931371
0.19647473560517037
30.367135135135133
-2315.251743203927
55.97226117156803
0.019647473560517038
2.9471210340775555
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 583.3091958422327
0.19325183302494442
1366.5259343671735
-23729.200552443155
17.32218407772823
0.019325183302494442
2.898777495374166
1
1
[1, 1, 1]
gt: 223.65899884523589
0.19647473560517037
27.76580963572268
-1816.0230259066423
48.654171226814384
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 81.74499668274015
0.19647473560517037
26.83451938895417
-807.2475477392888
25.369929384371712
0.019647473560517038
2.9471210340775555
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 680.7206750501216
0.19325183302494442
1363.6851324217068
-24408.40315910423
17.85368394769302
0.019325183302494442
2.898777495374166
1
1
[1, 1, 1]
gt: 260.37505588501006
0.19647473560517037
26.378698002350173
-2189.318519462969
57.967720409178085
0.019647473560517038
2.9471210340775555
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 517.6488012691265
0.19325183302494442
1363.5382610286078
-23322.44225072469
17.063090801834043
0.019325183302494442
2.898777495374166
1
1
[1, 1, 1]
gt: 334.4413231542279
0.19647473560517037
26.42978143360752
-2746.143754040418
68.75834781174846
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 11.969463259305845
0.19647473560517037
26.704846063454756
-288.2800580173955
10.051693581688605
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.219722679200938
-18.781098566392476
0.6400000000000003
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.333565217391303
-154.50898951821387
5.439999999999999
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.683290246768507
-130.02648883666274
4.549999999999996
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.92691891891892
-112.78732399529964
3.929999999999997
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
28.26485546415981
-88.62486101057578
3.0699999999999963
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
28.775689776733252
-51.5485066039953
1.7699999999999947
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.32581903642773
-10.877450434782608
0.36999999999999783
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.655896592244417
13.894870129259694
-0.4700000000000021
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.954538190364275
36.546835346650994
-1.2299999999999986
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.954538190364275
36.546835346650994
-1.2299999999999986
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.013480611045825
41.04443675675675
-1.379999999999996
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.00562162162162
40.44424573443008
-1.360000000000004
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.151012925969447
51.57322312573443
-1.730000000000002
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.241391304347825
58.51834961222091
-1.9600000000000029
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.3278401880141
65.18096507638073
-2.1800000000000033
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 313.2626468998559
0.19647473560517037
30.103858989424204
-2321.647604587253
56.37726219320576
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 174.8109885679439
0.19647473560517037
29.376902467685074
-1329.3805697879773
36.39405102768788
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 76.16272725638977
0.19647473560517037
29.298312573443006
-589.0452855168415
17.945486320385363
0.019647473560517038
2.9471210340775555
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 814.3423953073219
0.19325183302494442
1363.7005925683488
-28309.74109591297
20.698784248021138
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 803.2666097593421
0.19325183302494442
1363.352739268904
-34095.57980465521
24.920596450242606
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 685.9933543228614
0.19325183302494442
1363.267708462373
-37228.3916181564
27.20330075246522
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 577.0629760753715
0.19325183302494442
1366.2669769109202
-39560.33916107355
28.837432277599024
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 355.5800783516522
0.19325183302494442
1363.6155617618178
-39236.850433922824
28.657739296667188
0.019325183302494442
2.898777495374166
1
1
[1, 1, 1]
gt: 12.602362770005
0.19647473560517037
26.842378378378378
-283.69672115520115
9.857710511727241
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.628277320799057
-133.8982985663925
4.690000000000002
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.376902467685074
-7.061773537015275
0.23999999999999222
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.24329964747356
-17.02720789659224
0.5799999999999977
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.424056404230317
-3.533716004700352
0.11999999999999611
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.85630082256169
29.07048047003525
-0.9799999999999969
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.119576968272618
49.162399529964745
-1.6499999999999986
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.28461574618096
61.84727999999999
-2.0699999999999985
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.382853113983547
69.43071360752056
-2.3200000000000003
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
29.569447708578142
7.380082256169212
-0.2500000000000017
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.555750881316097
82.83720648648648
-2.760000000000001
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.602904817861337
86.50672582843711
-2.880000000000006
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.63041128084606
88.64989189189188
-2.95
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.63827027027027
89.26257870740307
-2.970000000000001
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.634340775558165
88.9562156521739
-2.9600000000000004
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
30.602904817861337
86.50672582843711
-2.880000000000006
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 333.1983390619881
0.19647473560517037
30.35141715628672
-2453.403296697803
58.60232055543863
0.019647473560517038
2.9471210340775555
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 598.6736332249144
0.19325183302494442
1366.638020430328
-24019.431477970124
17.532097341338464
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 781.687737978948
0.19325183302494442
1365.2234170125855
-31438.172720196402
22.953281489589205
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 863.1616850800897
0.19325183302494442
1364.1257466010038
-39141.10519293901
28.57748401463089
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 871.4000778563748
0.19325183302494442
1363.6310219084598
-46225.53181823513
33.737548905364
0.019325183302494442
2.898777495374166
0.9835963511018402
1.0000000000000002
[1.0, 1.0, 1.0]
gt: 765.8494509487858
0.19325183302494442
1366.2708419475807
-51087.88508628404
37.19650899402496
0.019325183302494442
2.898777495374166
1
1
[1, 1, 1]
gt: 181.55639399720675
0.19647473560517037
26.22544770857814
-1603.3701113029604
45.57616610663161
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 122.30441893465074
0.19647473560517037
26.382627497062277
-1144.6501250835884
34.514907058066086
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 12.852213060593387
0.19647473560517037
26.91310928319624
-280.7486641523522
9.739215788174983
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.25104582843713
-160.24037367802583
5.649999999999999
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.313917743830785
-155.8751765922444
5.490000000000001
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.600770857814336
-135.83131525264395
4.759999999999996
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
27.844399529964747
-118.64331243243242
4.139999999999997
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
28.084098707403054
-101.58512047003524
3.529999999999998
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
28.42596474735605
-77.00324286721505
2.6599999999999966
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
28.69317038777908
-57.58273692126909
1.9799999999999947
0.019647473560517038
2.9471210340775555
1
1
[1, 1, 1]
gt: 0.0
0.19647473560517037
28.9446580493537
-39.1386318213866
1.3400000000000034
0.019647473560517038
2.9471210340775555

In [8]:
res_df = prosumer.time_series.data_source.iloc[0].df
res_df.head(15)

,outlet_temperature_C,outlet_flow_rate_kg_h,energy_gain_W
2005-01-01 00:30:00+00:00,20.000000,0.0,-0.000000
2005-01-01 01:30:00+00:00,18.250000,0.0,-0.000000
2005-01-01 02:30:00+00:00,16.500000,0.0,-0.000000
2005-01-01 03:30:00+00:00,14.750000,0.0,-0.000000
2005-01-01 04:30:00+00:00,13.000000,0.0,-0.000000
2005-01-01 05:30:00+00:00,11.250000,0.0,-0.000000
2005-01-01 06:30:00+00:00,10.000000,0.0,-0.000000
2005-01-01 07:30:00+00:00,10.000000,0.0,0.000000
2005-01-01 08:30:00+00:00,19.921810,576.0,3730.974077
2005-01-01 09:30:00+00:00,25.937027,576.0,5016.419303
2005-01-01 10:30:00+00:00,31.524737,576.0,5503.245559
2005-01-01 11:30:00+00:00,36.506381,576.0,5504.813351
2005-01-01 12:30:00+00:00,38.372173,576.0,4373.465688
2005-01-01 13:30:00+00:00,38.236634,576.0,2971.100065
2005-01-01 14:30:00+00:00,32.044200,0.0,0.000000